"""
EmojiBlend — Streamlit Demo App
Team PPG | VAE Emoji Fusion

Run with: streamlit run app.py
Requires: emoji_encoder.keras, emoji_decoder.keras, emoji_index.json
          (all generated by the training notebook)
"""

import io, json, math, requests
from pathlib import Path

import numpy as np
import streamlit as st
from PIL import Image

# ── TF Import (lazy, only when models are loaded) ────────────────────────────
import tensorflow as tf

# ── Page Config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="EmojiBlend 🎨",
    page_icon="🎨",
    layout="wide",
)

# ── Styling ───────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main { background-color: #0f0f1a; color: #f0f0f0; }
    .stApp { background: linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 100%); }

    h1 { 
        background: linear-gradient(90deg, #a78bfa, #f472b6, #fb923c);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        font-size: 3rem !important; text-align: center; margin-bottom: 0;
    }
    .subtitle { 
        text-align: center; color: #9ca3af; font-size: 1.1rem; margin-top: 0.2rem;
    }
    .emoji-card {
        background: rgba(255,255,255,0.05);
        border: 1px solid rgba(255,255,255,0.1);
        border-radius: 16px; padding: 1rem; text-align: center;
        transition: all 0.2s;
    }
    .result-card {
        background: linear-gradient(135deg, rgba(167,139,250,0.15), rgba(244,114,182,0.15));
        border: 1px solid rgba(167,139,250,0.3);
        border-radius: 20px; padding: 1.5rem; text-align: center;
    }
    .blend-label {
        color: #a78bfa; font-size: 0.85rem; font-weight: 600;
        text-transform: uppercase; letter-spacing: 0.05em;
    }
    div[data-testid="stSelectbox"] label { color: #d1d5db !important; }
    .stSlider label { color: #d1d5db !important; }
    .section-header {
        font-size: 1.2rem; font-weight: 700; color: #a78bfa;
        border-bottom: 1px solid rgba(167,139,250,0.3);
        padding-bottom: 0.4rem; margin-top: 1.5rem;
    }
    .info-box {
        background: rgba(99, 102, 241, 0.1);
        border-left: 3px solid #6366f1;
        border-radius: 0 8px 8px 0;
        padding: 0.75rem 1rem; margin: 0.75rem 0;
        color: #c4b5fd; font-size: 0.92rem;
    }
</style>
""", unsafe_allow_html=True)


# ── Constants ─────────────────────────────────────────────────────────────────
IMG_SIZE    = 72
OPENMOJI_CDN = "https://cdn.jsdelivr.net/gh/hfg-gmuend/openmoji/color/72x72/{hexcode}.png"
INDEX_FILE  = Path("emoji_index.json")
ENCODER_PATH = "emoji_encoder.keras"
DECODER_PATH = "emoji_decoder.keras"

# Groups for the search filter
EMOJI_GROUPS = [
    "All Groups",
    "smileys-emotion", "people-body", "animals-nature",
    "food-drink", "travel-places", "activities",
    "objects", "symbols", "flags"
]


# ── Helpers ───────────────────────────────────────────────────────────────────

@st.cache_data(show_spinner=False)
def load_emoji_index():
    """Load the emoji index JSON, fall back to fetching from GitHub if missing."""
    if INDEX_FILE.exists():
        with open(INDEX_FILE, encoding="utf-8") as f:
            return json.load(f)
    # Fallback: fetch metadata from GitHub at runtime
    st.info("Downloading emoji index from OpenMoji…")
    r = requests.get(
        "https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/data/openmoji.json",
        timeout=15
    )
    data = r.json()
    # Keep only entries that have an emoji char and annotation
    index = [
        {"hexcode": e["hexcode"], "emoji": e.get("emoji",""), 
         "annotation": e.get("annotation",""), "group": e.get("group","")}
        for e in data if e.get("emoji") and e.get("annotation")
    ]
    return index


@st.cache_resource(show_spinner=False)
def load_models():
    """Load trained encoder + decoder. Returns (encoder, decoder) or (None, None)."""
    enc_path = Path(ENCODER_PATH)
    dec_path = Path(DECODER_PATH)
    if not enc_path.exists() or not dec_path.exists():
        return None, None
    try:
        enc = tf.keras.models.load_model(str(enc_path))
        dec = tf.keras.models.load_model(str(dec_path))
        return enc, dec
    except Exception as e:
        st.error(f"Model load error: {e}")
        return None, None


@st.cache_data(show_spinner=False)
def fetch_emoji_image(hexcode: str) -> np.ndarray:
    """Fetch a 72x72 OpenMoji PNG from CDN, return float32 RGB [0,1]."""
    url = OPENMOJI_CDN.format(hexcode=hexcode)
    resp = requests.get(url, timeout=8)
    img = Image.open(io.BytesIO(resp.content)).convert("RGBA").resize(
        (IMG_SIZE, IMG_SIZE), Image.LANCZOS
    )
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    return np.array(bg.convert("RGB"), dtype=np.float32) / 255.0


def arr_to_pil(arr: np.ndarray, upscale: int = 4) -> Image.Image:
    """Convert float32 [0,1] numpy array to a PIL image, optionally upscaled."""
    clipped = np.clip(arr * 255, 0, 255).astype(np.uint8)
    pil = Image.fromarray(clipped)
    if upscale > 1:
        new_size = (IMG_SIZE * upscale, IMG_SIZE * upscale)
        pil = pil.resize(new_size, Image.LANCZOS)
    return pil


def encode(encoder, img_arr: np.ndarray) -> np.ndarray:
    """Encode a single image → latent mean vector."""
    batch = np.expand_dims(img_arr, 0)
    z_mean, _, _ = encoder.predict(batch, verbose=0)
    return z_mean[0]


def decode(decoder, z: np.ndarray) -> np.ndarray:
    """Decode a latent vector → image array."""
    out = decoder.predict(np.expand_dims(z, 0), verbose=0)
    return np.clip(out[0], 0, 1)


def blend_latents(z_a, z_b, alpha):
    """Spherical linear interpolation (SLERP) for smoother blending."""
    # Normalize
    norm_a = np.linalg.norm(z_a)
    norm_b = np.linalg.norm(z_b)
    a_hat  = z_a / (norm_a + 1e-8)
    b_hat  = z_b / (norm_b + 1e-8)

    dot = np.clip(np.dot(a_hat, b_hat), -1.0, 1.0)
    theta = np.arccos(dot)

    if abs(theta) < 1e-6:
        # Nearly identical, fallback to linear
        z = (1 - alpha) * z_a + alpha * z_b
    else:
        z = (math.sin((1 - alpha) * theta) / math.sin(theta)) * z_a + \
            (math.sin(alpha * theta) / math.sin(theta)) * z_b

    return z


# ── Main App ──────────────────────────────────────────────────────────────────

def main():
    # Header
    st.markdown("<h1>🎨 EmojiBlend</h1>", unsafe_allow_html=True)
    st.markdown(
        '<p class="subtitle">Fuse two emojis into something new — powered by a Variational Autoencoder</p>',
        unsafe_allow_html=True
    )
    st.markdown("---")

    # Load assets
    emoji_index = load_emoji_index()
    encoder, decoder = load_models()

    # Model status banner
    if encoder is None:
        st.warning(
            "⚠️ **Models not found.** Run `EmojiBlend_VAE_Training.ipynb` first "
            "to generate `emoji_encoder.keras` and `emoji_decoder.keras`, "
            "then place them in the same folder as this app."
        )
        st.stop()
    else:
        st.success("✅ Trained VAE models loaded successfully!")

    # ── Sidebar ───────────────────────────────────────────────────────────────
    with st.sidebar:
        st.markdown("## ⚙️ Settings")
        group_filter = st.selectbox("Filter by Category", EMOJI_GROUPS)
        blend_steps  = st.slider("Interpolation Steps", 5, 13, 9, step=2)
        upscale      = st.slider("Preview Upscale", 2, 6, 4,
                                 help="Upscales the 72×72 output for display")
        show_strip   = st.checkbox("Show full interpolation strip", value=True)
        show_latent  = st.checkbox("Show latent vector info", value=False)

        st.markdown("---")
        st.markdown("### 📖 About")
        st.markdown("""
**EmojiBlend** uses a **Convolutional VAE** trained from scratch on the 
[OpenMoji](https://openmoji.org) dataset (~3,000 emojis).

Two emojis are encoded into latent vectors and blended via **SLERP 
(Spherical Linear Interpolation)** before decoding — producing smooth, 
novel in-between emojis.

**Team PPG** | CIT-U | 2026
        """)

    # ── Emoji Selector ────────────────────────────────────────────────────────
    filtered = emoji_index
    if group_filter != "All Groups":
        filtered = [e for e in emoji_index if e.get("group","").startswith(group_filter.replace("-","_").replace("-","_"))]
        # Flexible match
        g = group_filter.replace("-", "").lower()
        filtered = [e for e in emoji_index if g in e.get("group","").replace("-","").lower()]
        if not filtered:
            filtered = emoji_index  # fallback

    options     = [f"{e['emoji']}  {e['annotation']}" for e in filtered]
    hex_by_opt  = {f"{e['emoji']}  {e['annotation']}": e['hexcode'] for e in filtered}

    col1, col_plus, col2 = st.columns([5, 1, 5])

    with col1:
        st.markdown('<p class="section-header">🅰️ First Emoji</p>', unsafe_allow_html=True)
        choice_a = st.selectbox("Select Emoji A", options, index=0, key="emoji_a",
                                label_visibility="collapsed")
        hex_a    = hex_by_opt[choice_a]

    with col_plus:
        st.markdown("<br><br><br>", unsafe_allow_html=True)
        st.markdown("<h2 style='text-align:center; color:#f472b6;'>+</h2>",
                    unsafe_allow_html=True)

    with col2:
        st.markdown('<p class="section-header">🅱️ Second Emoji</p>', unsafe_allow_html=True)
        default_b = min(5, len(options) - 1)
        choice_b  = st.selectbox("Select Emoji B", options, index=default_b, key="emoji_b",
                                 label_visibility="collapsed")
        hex_b     = hex_by_opt[choice_b]

    # ── Blend Slider ──────────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown('<p class="section-header">🎚️ Blend Ratio</p>', unsafe_allow_html=True)
    alpha = st.slider(
        "Blend Ratio (0 = 100% A,  1 = 100% B)",
        min_value=0.0, max_value=1.0, value=0.5, step=0.01
    )

    # ── Generate Button ───────────────────────────────────────────────────────
    st.markdown("<br>", unsafe_allow_html=True)
    col_btn = st.columns([2, 2, 2])[1]
    with col_btn:
        blend_btn = st.button("✨ Blend Emojis!", use_container_width=True, type="primary")

    if blend_btn or True:   # Auto-generate on change
        with st.spinner("Encoding… blending… decoding…"):
            try:
                # Fetch images
                img_a = fetch_emoji_image(hex_a)
                img_b = fetch_emoji_image(hex_b)

                # Encode
                z_a = encode(encoder, img_a)
                z_b = encode(encoder, img_b)

                # Single blend
                z_blend  = blend_latents(z_a, z_b, alpha)
                blended  = decode(decoder, z_blend)

                # ── Result Display ────────────────────────────────────────────
                st.markdown("---")
                st.markdown('<p class="section-header">🎉 Result</p>', unsafe_allow_html=True)

                rc1, rc2, rc3, rc4, rc5 = st.columns([2, 1, 3, 1, 2])

                with rc1:
                    st.markdown('<div class="emoji-card">', unsafe_allow_html=True)
                    st.image(arr_to_pil(img_a, upscale), caption=choice_a.split("  ")[1],
                             use_column_width=True)
                    st.markdown(f'<p class="blend-label">Emoji A</p>', unsafe_allow_html=True)
                    st.markdown('</div>', unsafe_allow_html=True)

                with rc2:
                    st.markdown("<br><br>", unsafe_allow_html=True)
                    st.markdown(
                        f"<h3 style='text-align:center; color:#9ca3af;'>α={alpha:.2f}</h3>",
                        unsafe_allow_html=True
                    )

                with rc3:
                    st.markdown('<div class="result-card">', unsafe_allow_html=True)
                    pil_blend = arr_to_pil(blended, upscale)
                    st.image(pil_blend, caption="✨ Blended Emoji", use_column_width=True)
                    st.markdown(
                        f'<p class="blend-label">New emoji — α={alpha:.2f} blend</p>',
                        unsafe_allow_html=True
                    )

                    # Download button
                    buf = io.BytesIO()
                    pil_blend.save(buf, format="PNG")
                    st.download_button(
                        label="⬇️ Download PNG",
                        data=buf.getvalue(),
                        file_name=f"EmojiBlend_{hex_a}_{hex_b}_a{alpha:.2f}.png",
                        mime="image/png",
                        use_container_width=True
                    )
                    st.markdown('</div>', unsafe_allow_html=True)

                with rc4:
                    st.markdown("<br><br>", unsafe_allow_html=True)
                    st.markdown(
                        f"<h3 style='text-align:center; color:#9ca3af;'>→</h3>",
                        unsafe_allow_html=True
                    )

                with rc5:
                    st.markdown('<div class="emoji-card">', unsafe_allow_html=True)
                    st.image(arr_to_pil(img_b, upscale), caption=choice_b.split("  ")[1],
                             use_column_width=True)
                    st.markdown(f'<p class="blend-label">Emoji B</p>', unsafe_allow_html=True)
                    st.markdown('</div>', unsafe_allow_html=True)

                # ── Interpolation Strip ───────────────────────────────────────
                if show_strip:
                    st.markdown("---")
                    st.markdown(
                        '<p class="section-header">🌈 Full Interpolation Strip</p>',
                        unsafe_allow_html=True
                    )
                    alphas   = np.linspace(0, 1, blend_steps)
                    strip_cols = st.columns(blend_steps)
                    for col, a in zip(strip_cols, alphas):
                        z = blend_latents(z_a, z_b, float(a))
                        out_img = decode(decoder, z)
                        pil = arr_to_pil(out_img, upscale=3)
                        with col:
                            st.image(pil, use_column_width=True)
                            st.markdown(
                                f"<p style='text-align:center; font-size:0.75rem; color:#9ca3af;'>α={a:.2f}</p>",
                                unsafe_allow_html=True
                            )

                # ── Latent Info ────────────────────────────────────────────────
                if show_latent:
                    st.markdown("---")
                    st.markdown(
                        '<p class="section-header">🔬 Latent Space Info</p>',
                        unsafe_allow_html=True
                    )
                    li1, li2, li3 = st.columns(3)
                    with li1:
                        st.metric("Latent Dim", z_a.shape[0])
                    with li2:
                        dist = np.linalg.norm(z_a - z_b)
                        st.metric("Latent Distance (L2)", f"{dist:.3f}")
                    with li3:
                        cos_sim = np.dot(z_a, z_b) / (np.linalg.norm(z_a) * np.linalg.norm(z_b) + 1e-8)
                        st.metric("Cosine Similarity", f"{cos_sim:.3f}")

                    st.markdown(
                        '<div class="info-box">Blending uses <b>SLERP</b> (Spherical Linear Interpolation) '
                        'for a smooth, arc-preserving path through the VAE latent space — '
                        'producing more natural transitions than simple linear interpolation.</div>',
                        unsafe_allow_html=True
                    )

            except Exception as e:
                st.error(f"Something went wrong during blending: {e}")
                st.exception(e)


if __name__ == "__main__":
    main()
